export const COMBINE_ORDERS_CLEAR: "COMBINE_ORDERS_CLEAR" =
  "COMBINE_ORDERS_CLEAR";
export const COMBINE_ORDERS_UPDATED: "COMBINE_ORDERS_UPDATED" = "COMBINE_ORDERS_UPDATED";
export const COMBINE_ORDERS_COMPLITE: "COMBINE_ORDERS_COMPLITE" = "COMBINE_ORDERS_COMPLITE";
export const COMBINE_ORDERS_ERROR: "COMBINE_ORDERS_ERROR" = "COMBINE_ORDERS_ERROR";
