export const GET_ORDER_INFO_REQUEST: "GET_ORDER_INFO_REQUEST" = "GET_ORDER_INFO_REQUEST";
export const GET_ORDER_INFO_SUCCESS: "GET_ORDER_INFO_SUCCESS" = "GET_ORDER_INFO_SUCCESS";
export const GET_ORDER_INFO_ERROR: "GET_ORDER_INFO_ERROR" = "GET_ORDER_INFO_ERROR";
