export const WS_CONNECTION_FEED_START: "WS_CONNECTION_FEED_START" = "WS_CONNECTION_FEED_START";
export const WS_CONNECTION_USER_START: "WS_CONNECTION_USER_START" = "WS_CONNECTION_USER_START";

export const WS_CONNECTION_FEED_SUCCESS: "WS_CONNECTION_FEED_SUCCESS" =
  "WS_CONNECTION_FEED_SUCCESS";
export const WS_CONNECTION_USER_SUCCESS: "WS_CONNECTION_USER_SUCCESS" =
  "WS_CONNECTION_USER_SUCCESS";

export const WS_GET_FEED_DATA: "WS_GET_FEED_DATA" = "WS_GET_FEED_DATA";
export const WS_GET_USER_DATA: "WS_GET_USER_DATA" = "WS_GET_USER_DATA";

export const WS_CONNECTION_FEED_ERROR: "WS_CONNECTION_FEED_ERROR" = "WS_CONNECTION_FEED_ERROR";
export const WS_CONNECTION_USER_ERROR: "WS_CONNECTION_USER_ERROR" = "WS_CONNECTION_USER_ERROR";

export const WS_CONNECTION_FEED_CLOSED: "WS_CONNECTION_FEED_CLOSED" = "WS_CONNECTION_FEED_CLOSED";
export const WS_CONNECTION_USER_CLOSED: "WS_CONNECTION_USER_CLOSED" = "WS_CONNECTION_USER_CLOSED";
